apiVersion: batch/v1
kind: CronJob
metadata:
  name: traefik-allow-list-sync
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: traefik
          containers:
            - name: traefik-allow-list-sync
              image: 410954653531.dkr.ecr.eu-central-1.amazonaws.com/platform:traefik-ip-allowlist-sync
              env:
                - name: ALLOW_LIST_MIDDLEWARE_NAME
                  value: ip-allow-list
                - name: ALLOW_LIST_TRAEFIK_NAMESPACE
                  value: traefik-system
                # - name: ALLOW_LIST_DOMAINS
                #   value: example.com
          restartPolicy: OnFailure
